---
- name: "Resume a compute node"
  hosts: controller
  
  tasks:
  - name: Resume compute node
    command: scontrol update nodename="{{ compute }}" state=resume

  - name: Kubdeadm reset command to delete files
    shell: sudo kubeadm reset


